[package]
name = "svwc-snip"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
iced = { version = "0.12.1", features = ["debug"] }
xcap = "0.0.14"
